// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAppointments = `-- name: CountAppointments :one
SELECT count(*)
FROM appointments a
WHERE ($1::bigint  IS NULL OR a.donor_id  = $1::bigint)
  AND ($2::bigint IS NULL OR a.center_id = $2::bigint)
  AND ($3::bigint IS NULL OR a.donor_id = $3::bigint)
`

type CountAppointmentsParams struct {
	OwnerID     *int64
	CenterID    *int64
	DonorFilter *int64
}

func (q *Queries) CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointments, arg.OwnerID, arg.CenterID, arg.DonorFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointmentForRequest = `-- name: CreateAppointmentForRequest :one
INSERT INTO appointments (donation_request_id, donor_id, center_id, scheduled_at, status, created_by)
VALUES (
    $1,
    $2,
    $3,
    ($4::date + TIME '09:00') AT TIME ZONE 'Africa/Douala',
    'scheduled',
    $5
)
RETURNING id, donation_request_id, donor_id, center_id, scheduled_at, status
`

type CreateAppointmentForRequestParams struct {
	DonationRequestID *int32
	DonorID           int32
	CenterID          int64
	ScheduledDate     pgtype.Date
	CreatedBy         *int64
}

type CreateAppointmentForRequestRow struct {
	ID                int32
	DonationRequestID *int32
	DonorID           int32
	CenterID          int64
	ScheduledAt       pgtype.Timestamptz
	Status            AppointmentStatus
}

// Created only by approving a request, inside that request's transaction — never
// on its own. An appointment with no originating request is the shape of data
// the old `confirm` left behind when it deleted the row it came from.
func (q *Queries) CreateAppointmentForRequest(ctx context.Context, arg CreateAppointmentForRequestParams) (CreateAppointmentForRequestRow, error) {
	row := q.db.QueryRow(ctx, createAppointmentForRequest,
		arg.DonationRequestID,
		arg.DonorID,
		arg.CenterID,
		arg.ScheduledDate,
		arg.CreatedBy,
	)
	var i CreateAppointmentForRequestRow
	err := row.Scan(
		&i.ID,
		&i.DonationRequestID,
		&i.DonorID,
		&i.CenterID,
		&i.ScheduledAt,
		&i.Status,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT a.id, COALESCE(a.donation_request_id, 0)::bigint AS donation_request_id,
       a.donor_id, a.center_id, a.status, a.scheduled_at,
       (a.scheduled_at AT TIME ZONE 'Africa/Douala')::date AS scheduled_date,
       a.checked_in_at, a.completed_at, a.cancelled_at,
       p.full_name AS donor_name
FROM appointments a
JOIN donor_profiles p ON p.user_id = a.donor_id
WHERE a.id = $1
`

type GetAppointmentRow struct {
	ID                int32
	DonationRequestID int64
	DonorID           int32
	CenterID          int64
	Status            AppointmentStatus
	ScheduledAt       pgtype.Timestamptz
	ScheduledDate     pgtype.Date
	CheckedInAt       pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	DonorName         string
}

func (q *Queries) GetAppointment(ctx context.Context, id int32) (GetAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i GetAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.DonationRequestID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.ScheduledAt,
		&i.ScheduledDate,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DonorName,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many

SELECT a.id, COALESCE(a.donation_request_id, 0)::bigint AS donation_request_id,
       a.donor_id, a.center_id, a.status, a.scheduled_at,
       (a.scheduled_at AT TIME ZONE 'Africa/Douala')::date AS scheduled_date,
       a.checked_in_at, a.completed_at, a.cancelled_at,
       p.full_name AS donor_name
FROM appointments a
JOIN donor_profiles p ON p.user_id = a.donor_id
WHERE ($1::bigint  IS NULL OR a.donor_id  = $1::bigint)
  AND ($2::bigint IS NULL OR a.center_id = $2::bigint)
  AND ($3::bigint IS NULL OR a.donor_id = $3::bigint)
ORDER BY a.scheduled_at DESC
LIMIT $5 OFFSET $4
`

type ListAppointmentsParams struct {
	OwnerID     *int64
	CenterID    *int64
	DonorFilter *int64
	Off         int32
	Lim         int32
}

type ListAppointmentsRow struct {
	ID                int32
	DonationRequestID int64
	DonorID           int32
	CenterID          int64
	Status            AppointmentStatus
	ScheduledAt       pgtype.Timestamptz
	ScheduledDate     pgtype.Date
	CheckedInAt       pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	DonorName         string
}

// Appointments (WI-22). Replaces the hand-written SQL in internal/legacy.
//
// `scheduled_at` is TIMESTAMPTZ; the legacy handlers projected it to a date in
// Africa/Douala inside every query. That timezone is an assumption (schema Q6),
// so it is applied in exactly one place per query rather than scattered, and the
// full timestamp is returned alongside so a client is never forced to guess.
func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.OwnerID,
		arg.CenterID,
		arg.DonorFilter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsRow{}
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DonationRequestID,
			&i.DonorID,
			&i.CenterID,
			&i.Status,
			&i.ScheduledAt,
			&i.ScheduledDate,
			&i.CheckedInAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.DonorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
