// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :exec
UPDATE appointments
   SET status = 'cancelled', cancelled_at = now(), cancellation_reason = $2
WHERE id = $1
`

type CancelAppointmentParams struct {
	ID                 int32
	CancellationReason *string
}

// The column is `cancellation_reason` (read from the schema, not guessed), and
// there is no `cancelled_by`: who did it belongs in `audit_log`, which WI-27
// writes by trigger so no application path can skip it.
func (q *Queries) CancelAppointment(ctx context.Context, arg CancelAppointmentParams) error {
	_, err := q.db.Exec(ctx, cancelAppointment, arg.ID, arg.CancellationReason)
	return err
}

const countAppointments = `-- name: CountAppointments :one
SELECT count(*)
FROM appointments a
WHERE ($1::bigint  IS NULL OR a.donor_id  = $1::bigint)
  AND ($2::bigint IS NULL OR a.center_id = $2::bigint)
  AND ($3::bigint IS NULL OR a.donor_id = $3::bigint)
`

type CountAppointmentsParams struct {
	OwnerID     *int64
	CenterID    *int64
	DonorFilter *int64
}

func (q *Queries) CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointments, arg.OwnerID, arg.CenterID, arg.DonorFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointmentForRequest = `-- name: CreateAppointmentForRequest :one
WITH centre AS (
    SELECT id, capacity_per_slot FROM donation_centers
     WHERE id = $3 AND is_active
),
free AS (
    SELECT gs.seat
    FROM centre, generate_series(1, centre.capacity_per_slot) AS gs(seat)
    WHERE NOT EXISTS (
        SELECT 1 FROM appointments a
         WHERE a.center_id    = centre.id
           AND a.scheduled_at = $4::timestamptz
           AND a.slot_seat    = gs.seat
           AND a.status <> 'cancelled'
    )
    ORDER BY gs.seat
    LIMIT 1
)
INSERT INTO appointments (donation_request_id, donor_id, center_id, scheduled_at, slot_seat, status, created_by)
SELECT
    $1,
    $2,
    $3,
    $4::timestamptz,
    free.seat,
    'scheduled',
    $5
FROM free
RETURNING id, donation_request_id, donor_id, center_id, scheduled_at, slot_seat, status
`

type CreateAppointmentForRequestParams struct {
	DonationRequestID *int32
	DonorID           int32
	CenterID          int64
	ScheduledAt       pgtype.Timestamptz
	CreatedBy         *int64
}

type CreateAppointmentForRequestRow struct {
	ID                int32
	DonationRequestID *int32
	DonorID           int32
	CenterID          int64
	ScheduledAt       pgtype.Timestamptz
	SlotSeat          int16
	Status            AppointmentStatus
}

// Created only by approving a request, inside that request's transaction — never
// on its own. An appointment with no originating request is the shape of data
// the old `confirm` left behind when it deleted the row it came from.
// Books the appointment into the LOWEST FREE SEAT of its slot (WI-24).
//
// The seat is chosen in the same statement that inserts it, and the partial
// unique index `appointments_one_per_slot_seat` is what actually holds under
// concurrency: two callers can both compute seat 2, and exactly one of them
// commits it. The other gets 23505 and the service asks again, which is why
// this query is safe to retry — see `AppointmentSeatRetries`.
//
// `generate_series(1, capacity) EXCEPT taken` rather than `count(*) + 1`,
// because seats are freed by cancellation: with seats 1 and 3 live, the next
// booking belongs in 2, and `count(*) + 1` would say 3 and collide.
//
// An empty result means the slot is full. That is a real answer, not an error —
// `:one` turns it into pgx.ErrNoRows and the service maps it to a 409 naming the
// slot.
//
// The centre's capacity, activity and timezone are read here rather than passed
// in, so a caller cannot widen a slot by sending a bigger number. The trigger
// rejects an out-of-range seat anyway; this keeps the honest path from ever
// producing one.
func (q *Queries) CreateAppointmentForRequest(ctx context.Context, arg CreateAppointmentForRequestParams) (CreateAppointmentForRequestRow, error) {
	row := q.db.QueryRow(ctx, createAppointmentForRequest,
		arg.DonationRequestID,
		arg.DonorID,
		arg.CenterID,
		arg.ScheduledAt,
		arg.CreatedBy,
	)
	var i CreateAppointmentForRequestRow
	err := row.Scan(
		&i.ID,
		&i.DonationRequestID,
		&i.DonorID,
		&i.CenterID,
		&i.ScheduledAt,
		&i.SlotSeat,
		&i.Status,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT a.id, COALESCE(a.donation_request_id, 0)::bigint AS donation_request_id,
       a.donor_id, a.center_id, a.status, a.scheduled_at,
       (a.scheduled_at AT TIME ZONE 'Africa/Douala')::date AS scheduled_date,
       a.checked_in_at, a.completed_at, a.cancelled_at,
       p.full_name AS donor_name
FROM appointments a
JOIN donor_profiles p ON p.user_id = a.donor_id
WHERE a.id = $1
`

type GetAppointmentRow struct {
	ID                int32
	DonationRequestID int64
	DonorID           int32
	CenterID          int64
	Status            AppointmentStatus
	ScheduledAt       pgtype.Timestamptz
	ScheduledDate     pgtype.Date
	CheckedInAt       pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	DonorName         string
}

func (q *Queries) GetAppointment(ctx context.Context, id int32) (GetAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i GetAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.DonationRequestID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.ScheduledAt,
		&i.ScheduledDate,
		&i.CheckedInAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.DonorName,
	)
	return i, err
}

const getAppointmentForUpdate = `-- name: GetAppointmentForUpdate :one
SELECT id, donation_request_id, donor_id, center_id, status, scheduled_at
FROM appointments
WHERE id = $1
FOR UPDATE
`

type GetAppointmentForUpdateRow struct {
	ID                int32
	DonationRequestID *int32
	DonorID           int32
	CenterID          int64
	Status            AppointmentStatus
	ScheduledAt       pgtype.Timestamptz
}

// Locks the row for a cancel or reschedule, so the status check and the write
// cannot straddle another transaction's change.
func (q *Queries) GetAppointmentForUpdate(ctx context.Context, id int32) (GetAppointmentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentForUpdate, id)
	var i GetAppointmentForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.DonationRequestID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.ScheduledAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many

SELECT a.id, COALESCE(a.donation_request_id, 0)::bigint AS donation_request_id,
       a.donor_id, a.center_id, a.status, a.scheduled_at,
       (a.scheduled_at AT TIME ZONE 'Africa/Douala')::date AS scheduled_date,
       a.checked_in_at, a.completed_at, a.cancelled_at,
       p.full_name AS donor_name
FROM appointments a
JOIN donor_profiles p ON p.user_id = a.donor_id
WHERE ($1::bigint  IS NULL OR a.donor_id  = $1::bigint)
  AND ($2::bigint IS NULL OR a.center_id = $2::bigint)
  AND ($3::bigint IS NULL OR a.donor_id = $3::bigint)
ORDER BY a.scheduled_at DESC
LIMIT $5 OFFSET $4
`

type ListAppointmentsParams struct {
	OwnerID     *int64
	CenterID    *int64
	DonorFilter *int64
	Off         int32
	Lim         int32
}

type ListAppointmentsRow struct {
	ID                int32
	DonationRequestID int64
	DonorID           int32
	CenterID          int64
	Status            AppointmentStatus
	ScheduledAt       pgtype.Timestamptz
	ScheduledDate     pgtype.Date
	CheckedInAt       pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	DonorName         string
}

// Appointments (WI-22). Replaces the hand-written SQL in internal/legacy.
//
// `scheduled_at` is TIMESTAMPTZ; the legacy handlers projected it to a date in
// Africa/Douala inside every query. That timezone is an assumption (schema Q6),
// so it is applied in exactly one place per query rather than scattered, and the
// full timestamp is returned alongside so a client is never forced to guess.
func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.OwnerID,
		arg.CenterID,
		arg.DonorFilter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsRow{}
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DonationRequestID,
			&i.DonorID,
			&i.CenterID,
			&i.Status,
			&i.ScheduledAt,
			&i.ScheduledDate,
			&i.CheckedInAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.DonorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleAppointment = `-- name: RescheduleAppointment :one
UPDATE appointments
   SET scheduled_at = $2
WHERE id = $1
RETURNING id, donation_request_id, donor_id, center_id, status, scheduled_at
`

type RescheduleAppointmentParams struct {
	ID          int32
	ScheduledAt pgtype.Timestamptz
}

type RescheduleAppointmentRow struct {
	ID                int32
	DonationRequestID *int32
	DonorID           int32
	CenterID          int64
	Status            AppointmentStatus
	ScheduledAt       pgtype.Timestamptz
}

func (q *Queries) RescheduleAppointment(ctx context.Context, arg RescheduleAppointmentParams) (RescheduleAppointmentRow, error) {
	row := q.db.QueryRow(ctx, rescheduleAppointment, arg.ID, arg.ScheduledAt)
	var i RescheduleAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.DonationRequestID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.ScheduledAt,
	)
	return i, err
}

const sweepNoShows = `-- name: SweepNoShows :execrows
UPDATE appointments
   SET status = 'no_show'
WHERE status = 'scheduled'
  AND scheduled_at < now() - $1::interval
`

// The daily no-show sweep (FR-13).
//
// Idempotent by construction: it only touches rows still `scheduled` whose time
// has passed, so a second run in the same minute matches nothing. It writes NO
// deferral — not showing up is an administrative fact, and turning it into a
// clinical one would put a mark on a donor's record that no clinician made.
func (q *Queries) SweepNoShows(ctx context.Context, grace pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, sweepNoShows, grace)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
