// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpTokenVersion = `-- name: BumpTokenVersion :exec
UPDATE users SET token_version = token_version + 1 WHERE id = $1
`

// Invalidates every outstanding access token for this user immediately.
func (q *Queries) BumpTokenVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpTokenVersion, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (public_id, user_id, family_id, token_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, family_id, expires_at
`

type CreateSessionParams struct {
	PublicID  string
	UserID    int64
	FamilyID  string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent *string
}

type CreateSessionRow struct {
	ID        int64
	PublicID  string
	FamilyID  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.PublicID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FamilyID,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - INTERVAL '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, public_id, user_id, family_id, token_hash, issued_at, expires_at,
       rotated_at, revoked_at, revoked_reason
FROM sessions WHERE token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID            int64
	PublicID      string
	UserID        int64
	FamilyID      string
	TokenHash     []byte
	IssuedAt      pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	RotatedAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one

SELECT u.id, u.email, u.password_hash, u.role, u.status, u.token_version,
       u.hospital_id, u.failed_login_count, u.locked_until
FROM users u
WHERE u.email = $1::citext
`

type GetUserForLoginRow struct {
	ID               int64
	Email            string
	PasswordHash     string
	Role             UserRole
	Status           UserStatus
	TokenVersion     int32
	HospitalID       *int64
	FailedLoginCount int16
	LockedUntil      pgtype.Timestamptz
}

// Authentication queries (WI-17).
func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TokenVersion,
		&i.HospitalID,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const getUserForToken = `-- name: GetUserForToken :one
SELECT id, role, status, token_version, hospital_id
FROM users WHERE id = $1
`

type GetUserForTokenRow struct {
	ID           int64
	Role         UserRole
	Status       UserStatus
	TokenVersion int32
	HospitalID   *int64
}

func (q *Queries) GetUserForToken(ctx context.Context, id int64) (GetUserForTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserForToken, id)
	var i GetUserForTokenRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TokenVersion,
		&i.HospitalID,
	)
	return i, err
}

const markSessionRotated = `-- name: MarkSessionRotated :exec
UPDATE sessions SET rotated_at = now() WHERE id = $1 AND rotated_at IS NULL
`

func (q *Queries) MarkSessionRotated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSessionRotated, id)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :exec
UPDATE users SET failed_login_count = failed_login_count + 1
WHERE email = $1::citext
`

func (q *Queries) RecordFailedLogin(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, recordFailedLogin, email)
	return err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :execrows
UPDATE sessions
   SET revoked_at = now(), revoked_reason = $1
 WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeSessionFamilyParams struct {
	Reason   *string
	FamilyID string
}

// Reuse detection: one presented-twice token revokes every live row in the family.
func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionFamily, arg.Reason, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :execrows
UPDATE sessions
   SET revoked_at = now(), revoked_reason = $1
 WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsForUserParams struct {
	Reason *string
	UserID int64
}

func (q *Queries) RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForUser, arg.Reason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now(), failed_login_count = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}
