// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: centers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCenter = `-- name: CreateCenter :one
INSERT INTO donation_centers (code, name, address_line, city, region, phone, email,
                              capacity_per_slot, slot_minutes, opening_hours, timezone, is_active)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    COALESCE($8::smallint, 4),
    COALESCE($9::smallint, 30),
    COALESCE($10::jsonb, '{}'::jsonb),
    COALESCE($11::text, 'Africa/Douala'),
    -- Accepted on create, not dropped. ` + "`" + `POST {"is_active": false}` + "`" + ` used to
    -- return 201 with ` + "`" + `"is_active": true` + "`" + `, so a centre opened before anybody was
    -- ready to staff it. Absent still means active, which is the sensible
    -- default for a centre somebody just took the trouble to add.
    COALESCE($12::boolean, TRUE)
)
RETURNING id, code, name, address_line, city, region, phone, email,
          capacity_per_slot, slot_minutes, opening_hours, timezone, is_active
`

type CreateCenterParams struct {
	Code            string
	Name            string
	AddressLine     string
	City            string
	Region          string
	Phone           *string
	Email           *string
	CapacityPerSlot *int16
	SlotMinutes     *int16
	OpeningHours    []byte
	Timezone        *string
	IsActive        *bool
}

type CreateCenterRow struct {
	ID              int64
	Code            string
	Name            string
	AddressLine     string
	City            string
	Region          string
	Phone           *string
	Email           *string
	CapacityPerSlot int16
	SlotMinutes     int16
	OpeningHours    []byte
	Timezone        string
	IsActive        bool
}

func (q *Queries) CreateCenter(ctx context.Context, arg CreateCenterParams) (CreateCenterRow, error) {
	row := q.db.QueryRow(ctx, createCenter,
		arg.Code,
		arg.Name,
		arg.AddressLine,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.Email,
		arg.CapacityPerSlot,
		arg.SlotMinutes,
		arg.OpeningHours,
		arg.Timezone,
		arg.IsActive,
	)
	var i CreateCenterRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AddressLine,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Email,
		&i.CapacityPerSlot,
		&i.SlotMinutes,
		&i.OpeningHours,
		&i.Timezone,
		&i.IsActive,
	)
	return i, err
}

const defaultCenterID = `-- name: DefaultCenterID :one
SELECT id FROM donation_centers WHERE code = 'MAIN'
`

// The centre a booking lands at when the caller names none.
//
// `MAIN` by code, matching the `COALESCE` inside `CreateDonationRequest`. It is
// a query rather than a constant so the guard and the insert cannot disagree
// about which centre "the default" is — they already did once, and deactivating
// MAIN stopped nothing.
func (q *Queries) DefaultCenterID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, defaultCenterID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCenter = `-- name: GetCenter :one
SELECT id, code, name, address_line, city, region, phone, email,
       capacity_per_slot, slot_minutes, opening_hours, timezone, is_active
FROM donation_centers WHERE id = $1
`

type GetCenterRow struct {
	ID              int64
	Code            string
	Name            string
	AddressLine     string
	City            string
	Region          string
	Phone           *string
	Email           *string
	CapacityPerSlot int16
	SlotMinutes     int16
	OpeningHours    []byte
	Timezone        string
	IsActive        bool
}

func (q *Queries) GetCenter(ctx context.Context, id int64) (GetCenterRow, error) {
	row := q.db.QueryRow(ctx, getCenter, id)
	var i GetCenterRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AddressLine,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Email,
		&i.CapacityPerSlot,
		&i.SlotMinutes,
		&i.OpeningHours,
		&i.Timezone,
		&i.IsActive,
	)
	return i, err
}

const getCenterScheduling = `-- name: GetCenterScheduling :one

SELECT id, code, name, capacity_per_slot, slot_minutes, opening_hours, timezone, is_active
FROM donation_centers WHERE id = $1
`

type GetCenterSchedulingRow struct {
	ID              int64
	Code            string
	Name            string
	CapacityPerSlot int16
	SlotMinutes     int16
	OpeningHours    []byte
	Timezone        string
	IsActive        bool
}

// Donation centres (WI-24).
// The scheduling configuration one booking needs, in one read.
//
// `is_active` comes back rather than being filtered on, so the service can say
// "that centre is closed" instead of "no such centre". A donor told their usual
// centre does not exist will go looking for a bug; told it is closed, they will
// pick another one.
func (q *Queries) GetCenterScheduling(ctx context.Context, id int64) (GetCenterSchedulingRow, error) {
	row := q.db.QueryRow(ctx, getCenterScheduling, id)
	var i GetCenterSchedulingRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CapacityPerSlot,
		&i.SlotMinutes,
		&i.OpeningHours,
		&i.Timezone,
		&i.IsActive,
	)
	return i, err
}

const listCenters = `-- name: ListCenters :many
SELECT id, code, name, address_line, city, region, phone, email,
       capacity_per_slot, slot_minutes, opening_hours, timezone, is_active,
       count(*) OVER () AS total
FROM donation_centers
WHERE ($1::boolean IS NOT TRUE OR is_active)
  AND ($2::text IS NULL OR region = $2::text)
ORDER BY is_active DESC, name, id
LIMIT $4 OFFSET $3
`

type ListCentersParams struct {
	ActiveOnly *bool
	Region     *string
	Offset     int32
	Limit      int32
}

type ListCentersRow struct {
	ID              int64
	Code            string
	Name            string
	AddressLine     string
	City            string
	Region          string
	Phone           *string
	Email           *string
	CapacityPerSlot int16
	SlotMinutes     int16
	OpeningHours    []byte
	Timezone        string
	IsActive        bool
	Total           int64
}

// `id` is the tiebreaker, and it is not decoration: two centres sharing a
// name have no defined order without it, so paging could show one twice and
// skip the other.
func (q *Queries) ListCenters(ctx context.Context, arg ListCentersParams) ([]ListCentersRow, error) {
	rows, err := q.db.Query(ctx, listCenters,
		arg.ActiveOnly,
		arg.Region,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCentersRow{}
	for rows.Next() {
		var i ListCentersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AddressLine,
			&i.City,
			&i.Region,
			&i.Phone,
			&i.Email,
			&i.CapacityPerSlot,
			&i.SlotMinutes,
			&i.OpeningHours,
			&i.Timezone,
			&i.IsActive,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slotOccupancyOn = `-- name: SlotOccupancyOn :many
SELECT a.scheduled_at, count(*)::int AS booked
FROM appointments a
WHERE a.center_id = $1
  AND a.status <> 'cancelled'
  AND a.scheduled_at >= $2::timestamptz
  AND a.scheduled_at <  $3::timestamptz
GROUP BY a.scheduled_at
ORDER BY a.scheduled_at
`

type SlotOccupancyOnParams struct {
	CenterID int64
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

type SlotOccupancyOnRow struct {
	ScheduledAt pgtype.Timestamptz
	Booked      int32
}

// How full each slot is on one day, for a booking UI and for staff.
//
// Counts only live appointments: a cancelled one has given its seat back.
func (q *Queries) SlotOccupancyOn(ctx context.Context, arg SlotOccupancyOnParams) ([]SlotOccupancyOnRow, error) {
	rows, err := q.db.Query(ctx, slotOccupancyOn, arg.CenterID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlotOccupancyOnRow{}
	for rows.Next() {
		var i SlotOccupancyOnRow
		if err := rows.Scan(&i.ScheduledAt, &i.Booked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCenter = `-- name: UpdateCenter :one
UPDATE donation_centers
   SET name              = COALESCE($1, name),
       address_line      = COALESCE($2, address_line),
       city              = COALESCE($3, city),
       region            = COALESCE($4, region),
       phone             = COALESCE($5, phone),
       email             = COALESCE($6::citext, email),
       capacity_per_slot = COALESCE($7::smallint, capacity_per_slot),
       slot_minutes      = COALESCE($8::smallint, slot_minutes),
       opening_hours     = COALESCE($9::jsonb, opening_hours),
       timezone          = COALESCE($10::text, timezone),
       is_active         = COALESCE($11::boolean, is_active)
 WHERE id = $12
RETURNING id, code, name, address_line, city, region, phone, email,
          capacity_per_slot, slot_minutes, opening_hours, timezone, is_active
`

type UpdateCenterParams struct {
	Name            *string
	AddressLine     *string
	City            *string
	Region          *string
	Phone           *string
	Email           *string
	CapacityPerSlot *int16
	SlotMinutes     *int16
	OpeningHours    []byte
	Timezone        *string
	IsActive        *bool
	ID              int64
}

type UpdateCenterRow struct {
	ID              int64
	Code            string
	Name            string
	AddressLine     string
	City            string
	Region          string
	Phone           *string
	Email           *string
	CapacityPerSlot int16
	SlotMinutes     int16
	OpeningHours    []byte
	Timezone        string
	IsActive        bool
}

// PATCH semantics, for the same reason as the donor profile: a full-row UPDATE
// behind a partial form writes NULL over every field the form did not send.
//
// `code` is deliberately absent: it is the centre's stable identifier, printed
// on labels and quoted in reports, and renaming it silently would orphan every
// one of them. A centre that needs a different code is a different centre.
func (q *Queries) UpdateCenter(ctx context.Context, arg UpdateCenterParams) (UpdateCenterRow, error) {
	row := q.db.QueryRow(ctx, updateCenter,
		arg.Name,
		arg.AddressLine,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.Email,
		arg.CapacityPerSlot,
		arg.SlotMinutes,
		arg.OpeningHours,
		arg.Timezone,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateCenterRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AddressLine,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Email,
		&i.CapacityPerSlot,
		&i.SlotMinutes,
		&i.OpeningHours,
		&i.Timezone,
		&i.IsActive,
	)
	return i, err
}
