// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: donation_requests.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDonationRequest = `-- name: ApproveDonationRequest :exec
UPDATE donation_requests
   SET status = 'approved', reviewed_by = $2, reviewed_at = now()
 WHERE id = $1
`

type ApproveDonationRequestParams struct {
	ID         int32
	ReviewedBy *int64
}

func (q *Queries) ApproveDonationRequest(ctx context.Context, arg ApproveDonationRequestParams) error {
	_, err := q.db.Exec(ctx, approveDonationRequest, arg.ID, arg.ReviewedBy)
	return err
}

const cancelDonationRequest = `-- name: CancelDonationRequest :exec
UPDATE donation_requests
   SET status = 'cancelled', reviewed_by = $2, reviewed_at = now()
 WHERE id = $1
`

type CancelDonationRequestParams struct {
	ID         int32
	ReviewedBy *int64
}

func (q *Queries) CancelDonationRequest(ctx context.Context, arg CancelDonationRequestParams) error {
	_, err := q.db.Exec(ctx, cancelDonationRequest, arg.ID, arg.ReviewedBy)
	return err
}

const countDonationRequests = `-- name: CountDonationRequests :one
SELECT count(*)
FROM donation_requests r
WHERE ($1::donation_request_status IS NULL OR r.status = $1::donation_request_status)
  AND ($2::bigint  IS NULL OR r.donor_id  = $2::bigint)
  AND ($3::bigint IS NULL OR r.center_id = $3::bigint)
`

type CountDonationRequestsParams struct {
	Status   *DonationRequestStatus
	OwnerID  *int64
	CenterID *int64
}

func (q *Queries) CountDonationRequests(ctx context.Context, arg CountDonationRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDonationRequests, arg.Status, arg.OwnerID, arg.CenterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDonationRequest = `-- name: CreateDonationRequest :one
INSERT INTO donation_requests (donor_id, center_id, preferred_date, procedure, status, notes)
VALUES (
    $1,
    COALESCE($2::bigint, (SELECT id FROM donation_centers WHERE code = 'MAIN')),
    COALESCE($3::date, CURRENT_DATE + 7),
    COALESCE($4::donation_procedure, 'whole_blood'),
    'pending',
    $5
)
RETURNING id, donor_id, center_id, status, preferred_date, procedure, created_at
`

type CreateDonationRequestParams struct {
	DonorID       int32
	CenterID      *int64
	PreferredDate pgtype.Date
	Procedure     *DonationProcedure
	Notes         *string
}

type CreateDonationRequestRow struct {
	ID            int32
	DonorID       int32
	CenterID      int64
	Status        DonationRequestStatus
	PreferredDate pgtype.Date
	Procedure     DonationProcedure
	CreatedAt     pgtype.Timestamptz
}

// `procedure` is written, not left to the column default.
//
// It used to be omitted, so the row was always `whole_blood` — while the FR-19
// gate evaluated the procedure the CLIENT sent. A donor who gave whole blood
// eight days ago could post `{"procedure":"apheresis_platelet"}`, pass the
// 7-day platelet interval, and have a WHOLE-BLOOD request stored for approval.
// The gate and the row have to describe the same donation or the gate guards
// nothing.
//
// `preferred_date` keeps its `CURRENT_DATE + 7` default in SQL, but the service
// now resolves that date BEFORE the gate runs and passes it explicitly, so the
// date checked and the date stored are the same one. The default is left here
// for any caller that bypasses the service.
func (q *Queries) CreateDonationRequest(ctx context.Context, arg CreateDonationRequestParams) (CreateDonationRequestRow, error) {
	row := q.db.QueryRow(ctx, createDonationRequest,
		arg.DonorID,
		arg.CenterID,
		arg.PreferredDate,
		arg.Procedure,
		arg.Notes,
	)
	var i CreateDonationRequestRow
	err := row.Scan(
		&i.ID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.PreferredDate,
		&i.Procedure,
		&i.CreatedAt,
	)
	return i, err
}

const getDonationRequest = `-- name: GetDonationRequest :one
SELECT r.id, r.donor_id, r.center_id, r.status, r.preferred_date, r.created_at,
       r.rejection_reason, r.notes, r.reviewed_at,
       p.full_name AS donor_name, p.legacy_last_donation
FROM donation_requests r
JOIN donor_profiles p ON p.user_id = r.donor_id
WHERE r.id = $1
`

type GetDonationRequestRow struct {
	ID                 int32
	DonorID            int32
	CenterID           int64
	Status             DonationRequestStatus
	PreferredDate      pgtype.Date
	CreatedAt          pgtype.Timestamptz
	RejectionReason    *string
	Notes              *string
	ReviewedAt         pgtype.Timestamptz
	DonorName          string
	LegacyLastDonation pgtype.Date
}

func (q *Queries) GetDonationRequest(ctx context.Context, id int32) (GetDonationRequestRow, error) {
	row := q.db.QueryRow(ctx, getDonationRequest, id)
	var i GetDonationRequestRow
	err := row.Scan(
		&i.ID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.PreferredDate,
		&i.CreatedAt,
		&i.RejectionReason,
		&i.Notes,
		&i.ReviewedAt,
		&i.DonorName,
		&i.LegacyLastDonation,
	)
	return i, err
}

const getDonationRequestForUpdate = `-- name: GetDonationRequestForUpdate :one
SELECT id, donor_id, center_id, status, preferred_date, procedure
FROM donation_requests
WHERE id = $1
FOR UPDATE
`

type GetDonationRequestForUpdateRow struct {
	ID            int32
	DonorID       int32
	CenterID      int64
	Status        DonationRequestStatus
	PreferredDate pgtype.Date
	Procedure     DonationProcedure
}

// Locks the row for the duration of the approving/rejecting transaction.
//
// FOR UPDATE is what makes the status check meaningful: without it two staff
// approving the same request both read 'pending', both pass the check, and both
// insert an appointment. The UNIQUE on appointments.donation_request_id would
// catch the second as a constraint violation — a 500 rather than a clean 409.
func (q *Queries) GetDonationRequestForUpdate(ctx context.Context, id int32) (GetDonationRequestForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDonationRequestForUpdate, id)
	var i GetDonationRequestForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.DonorID,
		&i.CenterID,
		&i.Status,
		&i.PreferredDate,
		&i.Procedure,
	)
	return i, err
}

const hasOpenDonationRequest = `-- name: HasOpenDonationRequest :one
SELECT EXISTS (
    SELECT 1 FROM donation_requests WHERE donor_id = $1 AND status = 'pending'
)
`

func (q *Queries) HasOpenDonationRequest(ctx context.Context, donorID int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenDonationRequest, donorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDonationRequests = `-- name: ListDonationRequests :many

SELECT r.id, r.donor_id, r.center_id, r.status, r.preferred_date, r.created_at,
       r.rejection_reason, r.notes, r.reviewed_at,
       p.full_name AS donor_name, p.legacy_last_donation
FROM donation_requests r
JOIN donor_profiles p ON p.user_id = r.donor_id
WHERE ($1::donation_request_status IS NULL OR r.status = $1::donation_request_status)
  AND ($2::bigint  IS NULL OR r.donor_id  = $2::bigint)
  AND ($3::bigint IS NULL OR r.center_id = $3::bigint)
ORDER BY r.id
LIMIT $5 OFFSET $4
`

type ListDonationRequestsParams struct {
	Status   *DonationRequestStatus
	OwnerID  *int64
	CenterID *int64
	Off      int32
	Lim      int32
}

type ListDonationRequestsRow struct {
	ID                 int32
	DonorID            int32
	CenterID           int64
	Status             DonationRequestStatus
	PreferredDate      pgtype.Date
	CreatedAt          pgtype.Timestamptz
	RejectionReason    *string
	Notes              *string
	ReviewedAt         pgtype.Timestamptz
	DonorName          string
	LegacyLastDonation pgtype.Date
}

// Donation requests (WI-22). Replaces the hand-written SQL in internal/legacy.
//
// Every list query takes the scope predicate as parameters rather than by string
// concatenation. The legacy version appended " AND r.donor_id = $1" to build the
// authorization filter, which worked but put the security rule in a string. Here
// the caller passes the scope explicitly and a NULL means "not scoped this way",
// so a forgotten scope cannot silently widen the result set.
func (q *Queries) ListDonationRequests(ctx context.Context, arg ListDonationRequestsParams) ([]ListDonationRequestsRow, error) {
	rows, err := q.db.Query(ctx, listDonationRequests,
		arg.Status,
		arg.OwnerID,
		arg.CenterID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDonationRequestsRow{}
	for rows.Next() {
		var i ListDonationRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.DonorID,
			&i.CenterID,
			&i.Status,
			&i.PreferredDate,
			&i.CreatedAt,
			&i.RejectionReason,
			&i.Notes,
			&i.ReviewedAt,
			&i.DonorName,
			&i.LegacyLastDonation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectDonationRequest = `-- name: RejectDonationRequest :exec
UPDATE donation_requests
   SET status = 'rejected', rejection_reason = $2, notes = $3,
       reviewed_by = $4, reviewed_at = now()
 WHERE id = $1
`

type RejectDonationRequestParams struct {
	ID              int32
	RejectionReason *string
	Notes           *string
	ReviewedBy      *int64
}

// The schema CHECK (status <> 'rejected' OR rejection_reason IS NOT NULL) makes
// a reasonless rejection impossible at the storage layer; the domain decides
// whether the reason is one we recognise.
func (q *Queries) RejectDonationRequest(ctx context.Context, arg RejectDonationRequestParams) error {
	_, err := q.db.Exec(ctx, rejectDonationRequest,
		arg.ID,
		arg.RejectionReason,
		arg.Notes,
		arg.ReviewedBy,
	)
	return err
}
