// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: donors.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDonors = `-- name: CountDonors :one
SELECT count(*) FROM users u
JOIN donor_profiles p ON p.user_id = u.id
WHERE u.role = 'donor'
  AND ($1::text IS NULL
       OR p.full_name ILIKE '%' || $1::text || '%'
       OR u.email::text ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountDonors(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countDonors, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDonor = `-- name: CreateDonor :one
WITH new_user AS (
    INSERT INTO users (email, password_hash, role, status)
    VALUES ($1, $2, 'donor', 'active')
    RETURNING id
)
INSERT INTO donor_profiles (user_id, full_name, date_of_birth, gender,
                            blood_group, rhesus, contact_phone, address_line)
SELECT id, $3, $4, $5, $6, $7, $8, $9 FROM new_user
RETURNING user_id
`

type CreateDonorParams struct {
	Email        string
	PasswordHash string
	FullName     string
	DateOfBirth  pgtype.Date
	Gender       Gender
	BloodGroup   *BloodGroup
	Rhesus       *Rhesus
	ContactPhone string
	AddressLine  *string
}

func (q *Queries) CreateDonor(ctx context.Context, arg CreateDonorParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDonor,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.BloodGroup,
		arg.Rhesus,
		arg.ContactPhone,
		arg.AddressLine,
	)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getDonorByID = `-- name: GetDonorByID :one

SELECT u.id, u.email, u.role, u.status,
       p.full_name, p.date_of_birth, p.gender, p.blood_group, p.rhesus,
       p.contact_phone, p.address_line, p.city, p.region, p.national_id,
       p.emergency_contact_name, p.emergency_contact_phone,
       p.total_donations, p.legacy_last_donation
FROM users u
JOIN donor_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.role = 'donor'
`

type GetDonorByIDRow struct {
	ID                    int64
	Email                 string
	Role                  UserRole
	Status                UserStatus
	FullName              string
	DateOfBirth           pgtype.Date
	Gender                Gender
	BloodGroup            *BloodGroup
	Rhesus                *Rhesus
	ContactPhone          string
	AddressLine           *string
	City                  *string
	Region                *string
	NationalID            *string
	EmergencyContactName  *string
	EmergencyContactPhone *string
	TotalDonations        int32
	LegacyLastDonation    pgtype.Date
}

// Donor queries. The strangler pilot for WI-11: donors move to the layered
// structure first, everything else keeps working through internal/legacy.
//
// Note these read `users` JOIN `donor_profiles`, never the legacy `donors` table.
func (q *Queries) GetDonorByID(ctx context.Context, id int64) (GetDonorByIDRow, error) {
	row := q.db.QueryRow(ctx, getDonorByID, id)
	var i GetDonorByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.BloodGroup,
		&i.Rhesus,
		&i.ContactPhone,
		&i.AddressLine,
		&i.City,
		&i.Region,
		&i.NationalID,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.TotalDonations,
		&i.LegacyLastDonation,
	)
	return i, err
}

const getDonorEligibility = `-- name: GetDonorEligibility :one
SELECT donor_id, full_name, blood_group, rhesus, age_years, last_donated_at,
       donations_last_12m, permanently_deferred, deferred_until,
       next_eligible_on, is_eligible_today, reason
FROM donor_eligibility WHERE donor_id = $1
`

func (q *Queries) GetDonorEligibility(ctx context.Context, donorID int64) (DonorEligibility, error) {
	row := q.db.QueryRow(ctx, getDonorEligibility, donorID)
	var i DonorEligibility
	err := row.Scan(
		&i.DonorID,
		&i.FullName,
		&i.BloodGroup,
		&i.Rhesus,
		&i.AgeYears,
		&i.LastDonatedAt,
		&i.DonationsLast12m,
		&i.PermanentlyDeferred,
		&i.DeferredUntil,
		&i.NextEligibleOn,
		&i.IsEligibleToday,
		&i.Reason,
	)
	return i, err
}

const listDonors = `-- name: ListDonors :many
SELECT u.id, u.email, u.status,
       p.full_name, p.blood_group, p.rhesus, p.contact_phone, p.total_donations
FROM users u
JOIN donor_profiles p ON p.user_id = u.id
WHERE u.role = 'donor'
  AND ($1::text IS NULL
       OR p.full_name ILIKE '%' || $1::text || '%'
       OR u.email::text ILIKE '%' || $1::text || '%')
ORDER BY p.full_name
LIMIT $3 OFFSET $2
`

type ListDonorsParams struct {
	Search *string
	Off    int32
	Lim    int32
}

type ListDonorsRow struct {
	ID             int64
	Email          string
	Status         UserStatus
	FullName       string
	BloodGroup     *BloodGroup
	Rhesus         *Rhesus
	ContactPhone   string
	TotalDonations int32
}

func (q *Queries) ListDonors(ctx context.Context, arg ListDonorsParams) ([]ListDonorsRow, error) {
	rows, err := q.db.Query(ctx, listDonors, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDonorsRow{}
	for rows.Next() {
		var i ListDonorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.FullName,
			&i.BloodGroup,
			&i.Rhesus,
			&i.ContactPhone,
			&i.TotalDonations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDonorProfile = `-- name: UpdateDonorProfile :exec
UPDATE donor_profiles
   SET full_name = $2, date_of_birth = $3, gender = $4,
       blood_group = $5, rhesus = $6, contact_phone = $7,
       address_line = $8, city = $9, region = $10,
       national_id = $11, emergency_contact_name = $12, emergency_contact_phone = $13
 WHERE user_id = $1
`

type UpdateDonorProfileParams struct {
	UserID                int64
	FullName              string
	DateOfBirth           pgtype.Date
	Gender                Gender
	BloodGroup            *BloodGroup
	Rhesus                *Rhesus
	ContactPhone          string
	AddressLine           *string
	City                  *string
	Region                *string
	NationalID            *string
	EmergencyContactName  *string
	EmergencyContactPhone *string
}

func (q *Queries) UpdateDonorProfile(ctx context.Context, arg UpdateDonorProfileParams) error {
	_, err := q.db.Exec(ctx, updateDonorProfile,
		arg.UserID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.BloodGroup,
		arg.Rhesus,
		arg.ContactPhone,
		arg.AddressLine,
		arg.City,
		arg.Region,
		arg.NationalID,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
	)
	return err
}
