// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one

INSERT INTO idempotency_keys (idem_key, actor_id, endpoint, fingerprint)
VALUES ($1, $2, $3, $4)
ON CONFLICT (actor_id, idem_key) DO NOTHING
RETURNING id, idem_key, actor_id, endpoint, fingerprint, response_status, response_body, created_at, completed_at, expires_at
`

type ClaimIdempotencyKeyParams struct {
	IdemKey     string
	ActorID     int64
	Endpoint    string
	Fingerprint []byte
}

// Idempotency-key storage (TRD §6.4). See migration 000016.
// Claim the key for this request, or tell us who already holds it.
//
// The INSERT ... ON CONFLICT DO NOTHING is the whole concurrency story: two
// simultaneous retries race here, exactly one inserts, and the loser gets no
// row back and must then read the existing one. Doing this as SELECT-then-INSERT
// would leave a window in which both callers decide they are first.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.IdemKey,
		arg.ActorID,
		arg.Endpoint,
		arg.Fingerprint,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdemKey,
		&i.ActorID,
		&i.Endpoint,
		&i.Fingerprint,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET response_status = $3,
    response_body   = $4,
    completed_at    = now()
WHERE actor_id = $1 AND idem_key = $2
`

type CompleteIdempotencyKeyParams struct {
	ActorID        int64
	IdemKey        string
	ResponseStatus *int32
	ResponseBody   []byte
}

// Store the response so a later retry can be answered without re-executing.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ActorID,
		arg.IdemKey,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, idem_key, actor_id, endpoint, fingerprint, response_status, response_body, created_at, completed_at, expires_at
FROM idempotency_keys
WHERE actor_id = $1 AND idem_key = $2
`

type GetIdempotencyKeyParams struct {
	ActorID int64
	IdemKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorID, arg.IdemKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.IdemKey,
		&i.ActorID,
		&i.Endpoint,
		&i.Fingerprint,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE actor_id = $1 AND idem_key = $2 AND response_status IS NULL
`

type ReleaseIdempotencyKeyParams struct {
	ActorID int64
	IdemKey string
}

// Release a claim whose handler never produced a storable response, so the
// client can retry instead of being told for 24 hours that a request it never
// completed is still in flight.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.ActorID, arg.IdemKey)
	return err
}

const sweepIdempotencyKeys = `-- name: SweepIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) SweepIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
