// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentStatus string

const (
	AppointmentStatusScheduled AppointmentStatus = "scheduled"
	AppointmentStatusCheckedIn AppointmentStatus = "checked_in"
	AppointmentStatusCompleted AppointmentStatus = "completed"
	AppointmentStatusNoShow    AppointmentStatus = "no_show"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	AppointmentStatusDeferred  AppointmentStatus = "deferred"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type BloodGroup string

const (
	BloodGroupA  BloodGroup = "A"
	BloodGroupB  BloodGroup = "B"
	BloodGroupAB BloodGroup = "AB"
	BloodGroupO  BloodGroup = "O"
)

func (e *BloodGroup) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BloodGroup(s)
	case string:
		*e = BloodGroup(s)
	default:
		return fmt.Errorf("unsupported scan type for BloodGroup: %T", src)
	}
	return nil
}

type NullBloodGroup struct {
	BloodGroup BloodGroup
	Valid      bool // Valid is true if BloodGroup is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBloodGroup) Scan(value interface{}) error {
	if value == nil {
		ns.BloodGroup, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BloodGroup.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBloodGroup) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BloodGroup), nil
}

type BloodRequestStatus string

const (
	BloodRequestStatusPending            BloodRequestStatus = "pending"
	BloodRequestStatusApproved           BloodRequestStatus = "approved"
	BloodRequestStatusPartiallyFulfilled BloodRequestStatus = "partially_fulfilled"
	BloodRequestStatusFulfilled          BloodRequestStatus = "fulfilled"
	BloodRequestStatusRejected           BloodRequestStatus = "rejected"
	BloodRequestStatusCancelled          BloodRequestStatus = "cancelled"
	BloodRequestStatusExpired            BloodRequestStatus = "expired"
)

func (e *BloodRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BloodRequestStatus(s)
	case string:
		*e = BloodRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BloodRequestStatus: %T", src)
	}
	return nil
}

type NullBloodRequestStatus struct {
	BloodRequestStatus BloodRequestStatus
	Valid              bool // Valid is true if BloodRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBloodRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BloodRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BloodRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBloodRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BloodRequestStatus), nil
}

type BloodUnitStatus string

const (
	BloodUnitStatusQuarantined BloodUnitStatus = "quarantined"
	BloodUnitStatusAvailable   BloodUnitStatus = "available"
	BloodUnitStatusReserved    BloodUnitStatus = "reserved"
	BloodUnitStatusIssued      BloodUnitStatus = "issued"
	BloodUnitStatusTransfused  BloodUnitStatus = "transfused"
	BloodUnitStatusExpired     BloodUnitStatus = "expired"
	BloodUnitStatusDiscarded   BloodUnitStatus = "discarded"
	BloodUnitStatusRecalled    BloodUnitStatus = "recalled"
)

func (e *BloodUnitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BloodUnitStatus(s)
	case string:
		*e = BloodUnitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BloodUnitStatus: %T", src)
	}
	return nil
}

type NullBloodUnitStatus struct {
	BloodUnitStatus BloodUnitStatus
	Valid           bool // Valid is true if BloodUnitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBloodUnitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BloodUnitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BloodUnitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBloodUnitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BloodUnitStatus), nil
}

type ComponentType string

const (
	ComponentTypeWholeBlood        ComponentType = "whole_blood"
	ComponentTypePackedRedCells    ComponentType = "packed_red_cells"
	ComponentTypeFreshFrozenPlasma ComponentType = "fresh_frozen_plasma"
	ComponentTypePlatelets         ComponentType = "platelets"
	ComponentTypeCryoprecipitate   ComponentType = "cryoprecipitate"
)

func (e *ComponentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComponentType(s)
	case string:
		*e = ComponentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ComponentType: %T", src)
	}
	return nil
}

type NullComponentType struct {
	ComponentType ComponentType
	Valid         bool // Valid is true if ComponentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComponentType) Scan(value interface{}) error {
	if value == nil {
		ns.ComponentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComponentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComponentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComponentType), nil
}

type CrossmatchResult string

const (
	CrossmatchResultNotRequired  CrossmatchResult = "not_required"
	CrossmatchResultCompatible   CrossmatchResult = "compatible"
	CrossmatchResultIncompatible CrossmatchResult = "incompatible"
)

func (e *CrossmatchResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrossmatchResult(s)
	case string:
		*e = CrossmatchResult(s)
	default:
		return fmt.Errorf("unsupported scan type for CrossmatchResult: %T", src)
	}
	return nil
}

type NullCrossmatchResult struct {
	CrossmatchResult CrossmatchResult
	Valid            bool // Valid is true if CrossmatchResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrossmatchResult) Scan(value interface{}) error {
	if value == nil {
		ns.CrossmatchResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrossmatchResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrossmatchResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrossmatchResult), nil
}

type DeferralType string

const (
	DeferralTypeTemporary DeferralType = "temporary"
	DeferralTypePermanent DeferralType = "permanent"
)

func (e *DeferralType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeferralType(s)
	case string:
		*e = DeferralType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeferralType: %T", src)
	}
	return nil
}

type NullDeferralType struct {
	DeferralType DeferralType
	Valid        bool // Valid is true if DeferralType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeferralType) Scan(value interface{}) error {
	if value == nil {
		ns.DeferralType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeferralType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeferralType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeferralType), nil
}

type DonationProcedure string

const (
	DonationProcedureWholeBlood        DonationProcedure = "whole_blood"
	DonationProcedureApheresisPlatelet DonationProcedure = "apheresis_platelet"
	DonationProcedureApheresisPlasma   DonationProcedure = "apheresis_plasma"
	DonationProcedureDoubleRedCell     DonationProcedure = "double_red_cell"
)

func (e *DonationProcedure) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DonationProcedure(s)
	case string:
		*e = DonationProcedure(s)
	default:
		return fmt.Errorf("unsupported scan type for DonationProcedure: %T", src)
	}
	return nil
}

type NullDonationProcedure struct {
	DonationProcedure DonationProcedure
	Valid             bool // Valid is true if DonationProcedure is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDonationProcedure) Scan(value interface{}) error {
	if value == nil {
		ns.DonationProcedure, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DonationProcedure.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDonationProcedure) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DonationProcedure), nil
}

type DonationRequestStatus string

const (
	DonationRequestStatusPending   DonationRequestStatus = "pending"
	DonationRequestStatusApproved  DonationRequestStatus = "approved"
	DonationRequestStatusRejected  DonationRequestStatus = "rejected"
	DonationRequestStatusCancelled DonationRequestStatus = "cancelled"
	DonationRequestStatusExpired   DonationRequestStatus = "expired"
)

func (e *DonationRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DonationRequestStatus(s)
	case string:
		*e = DonationRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DonationRequestStatus: %T", src)
	}
	return nil
}

type NullDonationRequestStatus struct {
	DonationRequestStatus DonationRequestStatus
	Valid                 bool // Valid is true if DonationRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDonationRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DonationRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DonationRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDonationRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DonationRequestStatus), nil
}

type Gender string

const (
	GenderMale        Gender = "male"
	GenderFemale      Gender = "female"
	GenderOther       Gender = "other"
	GenderUndisclosed Gender = "undisclosed"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type HospitalStatus string

const (
	HospitalStatusPendingApproval HospitalStatus = "pending_approval"
	HospitalStatusActive          HospitalStatus = "active"
	HospitalStatusSuspended       HospitalStatus = "suspended"
)

func (e *HospitalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HospitalStatus(s)
	case string:
		*e = HospitalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HospitalStatus: %T", src)
	}
	return nil
}

type NullHospitalStatus struct {
	HospitalStatus HospitalStatus
	Valid          bool // Valid is true if HospitalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHospitalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HospitalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HospitalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHospitalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HospitalStatus), nil
}

type IssuanceOutcome string

const (
	IssuanceOutcomePending    IssuanceOutcome = "pending"
	IssuanceOutcomeTransfused IssuanceOutcome = "transfused"
	IssuanceOutcomeReturned   IssuanceOutcome = "returned"
	IssuanceOutcomeExpired    IssuanceOutcome = "expired"
	IssuanceOutcomeDiscarded  IssuanceOutcome = "discarded"
)

func (e *IssuanceOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssuanceOutcome(s)
	case string:
		*e = IssuanceOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for IssuanceOutcome: %T", src)
	}
	return nil
}

type NullIssuanceOutcome struct {
	IssuanceOutcome IssuanceOutcome
	Valid           bool // Valid is true if IssuanceOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssuanceOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.IssuanceOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssuanceOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssuanceOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssuanceOutcome), nil
}

type NotificationChannel string

const (
	NotificationChannelEmail NotificationChannel = "email"
	NotificationChannelSms   NotificationChannel = "sms"
	NotificationChannelInApp NotificationChannel = "in_app"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel
	Valid               bool // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type NotificationStatus string

const (
	NotificationStatusQueued    NotificationStatus = "queued"
	NotificationStatusSent      NotificationStatus = "sent"
	NotificationStatusDelivered NotificationStatus = "delivered"
	NotificationStatusFailed    NotificationStatus = "failed"
	NotificationStatusCancelled NotificationStatus = "cancelled"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus
	Valid              bool // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type Rhesus string

const (
	RhesusPositive Rhesus = "positive"
	RhesusNegative Rhesus = "negative"
)

func (e *Rhesus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rhesus(s)
	case string:
		*e = Rhesus(s)
	default:
		return fmt.Errorf("unsupported scan type for Rhesus: %T", src)
	}
	return nil
}

type NullRhesus struct {
	Rhesus Rhesus
	Valid  bool // Valid is true if Rhesus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRhesus) Scan(value interface{}) error {
	if value == nil {
		ns.Rhesus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rhesus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRhesus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rhesus), nil
}

type ScreeningOutcome string

const (
	ScreeningOutcomePassed            ScreeningOutcome = "passed"
	ScreeningOutcomeDeferredTemporary ScreeningOutcome = "deferred_temporary"
	ScreeningOutcomeDeferredPermanent ScreeningOutcome = "deferred_permanent"
)

func (e *ScreeningOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScreeningOutcome(s)
	case string:
		*e = ScreeningOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for ScreeningOutcome: %T", src)
	}
	return nil
}

type NullScreeningOutcome struct {
	ScreeningOutcome ScreeningOutcome
	Valid            bool // Valid is true if ScreeningOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScreeningOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.ScreeningOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScreeningOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScreeningOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScreeningOutcome), nil
}

type StorageKind string

const (
	StorageKindFridge           StorageKind = "fridge"
	StorageKindFreezer          StorageKind = "freezer"
	StorageKindPlateletAgitator StorageKind = "platelet_agitator"
	StorageKindTransportBox     StorageKind = "transport_box"
)

func (e *StorageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageKind(s)
	case string:
		*e = StorageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageKind: %T", src)
	}
	return nil
}

type NullStorageKind struct {
	StorageKind StorageKind
	Valid       bool // Valid is true if StorageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageKind) Scan(value interface{}) error {
	if value == nil {
		ns.StorageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageKind), nil
}

type TestResultStatus string

const (
	TestResultStatusPending       TestResultStatus = "pending"
	TestResultStatusNonReactive   TestResultStatus = "non_reactive"
	TestResultStatusReactive      TestResultStatus = "reactive"
	TestResultStatusIndeterminate TestResultStatus = "indeterminate"
)

func (e *TestResultStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestResultStatus(s)
	case string:
		*e = TestResultStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestResultStatus: %T", src)
	}
	return nil
}

type NullTestResultStatus struct {
	TestResultStatus TestResultStatus
	Valid            bool // Valid is true if TestResultStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestResultStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestResultStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestResultStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestResultStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestResultStatus), nil
}

type UrgencyLevel string

const (
	UrgencyLevelRoutine   UrgencyLevel = "routine"
	UrgencyLevelUrgent    UrgencyLevel = "urgent"
	UrgencyLevelEmergency UrgencyLevel = "emergency"
)

func (e *UrgencyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrgencyLevel(s)
	case string:
		*e = UrgencyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for UrgencyLevel: %T", src)
	}
	return nil
}

type NullUrgencyLevel struct {
	UrgencyLevel UrgencyLevel
	Valid        bool // Valid is true if UrgencyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrgencyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.UrgencyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrgencyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrgencyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrgencyLevel), nil
}

type UserRole string

const (
	UserRoleDonor            UserRole = "donor"
	UserRoleStaff            UserRole = "staff"
	UserRoleLabTech          UserRole = "lab_tech"
	UserRoleInventoryManager UserRole = "inventory_manager"
	UserRoleHospitalUser     UserRole = "hospital_user"
	UserRoleAdmin            UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusPendingVerification UserStatus = "pending_verification"
	UserStatusActive              UserStatus = "active"
	UserStatusSuspended           UserStatus = "suspended"
	UserStatusDeactivated         UserStatus = "deactivated"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AboCompatibility struct {
	ComponentClass  string
	RecipientGroup  BloodGroup
	RecipientRhesus Rhesus
	DonorGroup      BloodGroup
	DonorRhesus     Rhesus
	PreferenceRank  int16
}

type ActivePolicy struct {
	Key           string
	Region        string
	Value         []byte
	EffectiveFrom pgtype.Date
}

type Appointment struct {
	ID                 int32
	DonationRequestID  *int32
	DonorID            int32
	CenterID           int64
	ScheduledAt        pgtype.Timestamptz
	Procedure          DonationProcedure
	Status             AppointmentStatus
	CheckedInAt        pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason *string
	CreatedBy          *int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AuditLog struct {
	ID         int64
	ActorID    *int64
	ActorRole  *UserRole
	Action     string
	EntityType string
	EntityID   string
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	UserAgent  *string
	RequestID  *string
	CreatedAt  pgtype.Timestamptz
}

type AuditLog2026m09 struct {
	ID         int64
	ActorID    *int64
	ActorRole  *UserRole
	Action     string
	EntityType string
	EntityID   string
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	UserAgent  *string
	RequestID  *string
	CreatedAt  pgtype.Timestamptz
}

type AuditLogDefault struct {
	ID         int64
	ActorID    *int64
	ActorRole  *UserRole
	Action     string
	EntityType string
	EntityID   string
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	UserAgent  *string
	RequestID  *string
	CreatedAt  pgtype.Timestamptz
}

type BloodRequest struct {
	ID              int64
	HospitalID      int64
	RequestedBy     int64
	PatientRef      string
	PatientAgeYears *int16
	BloodGroup      BloodGroup
	Rhesus          Rhesus
	ComponentType   ComponentType
	UnitsRequested  int16
	UnitsFulfilled  int16
	Urgency         UrgencyLevel
	NeededBy        pgtype.Timestamptz
	Indication      *string
	Status          BloodRequestStatus
	ReviewedBy      *int64
	ReviewedAt      pgtype.Timestamptz
	RejectionReason *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type BloodUnit struct {
	ID                int64
	UnitCode          string
	DonationID        int64
	ParentUnitID      *int64
	ComponentType     ComponentType
	BloodGroup        BloodGroup
	Rhesus            Rhesus
	VolumeMl          int32
	CollectedAt       pgtype.Timestamptz
	ProcessedAt       pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	Status            BloodUnitStatus
	StorageLocationID *int64
	DiscardReason     *string
	Version           int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Deferral struct {
	ID          int64
	DonorID     int64
	ScreeningID *int64
	Type        DeferralType
	ReasonCode  *string
	Reason      string
	StartsOn    pgtype.Date
	EndsOn      pgtype.Date
	LiftedAt    pgtype.Timestamptz
	LiftedBy    *int64
	CreatedBy   *int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Donation struct {
	ID                 int64
	AppointmentID      int64
	DonorID            int64
	CenterID           int64
	Procedure          DonationProcedure
	CollectedAt        pgtype.Timestamptz
	VolumeMl           int32
	BagLotNumber       string
	Anticoagulant      string
	PhlebotomistID     int64
	HadAdverseReaction bool
	AdverseReaction    *string
	Notes              *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type DonationCenter struct {
	ID              int64
	Code            string
	Name            string
	AddressLine     string
	City            string
	Region          string
	Phone           *string
	Email           *string
	Latitude        pgtype.Numeric
	Longitude       pgtype.Numeric
	CapacityPerSlot int16
	SlotMinutes     int16
	OpeningHours    []byte
	Timezone        string
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type DonationRequest struct {
	ID              int32
	DonorID         int32
	CreatedAt       pgtype.Timestamptz
	CenterID        int64
	PreferredDate   pgtype.Date
	Procedure       DonationProcedure
	Status          DonationRequestStatus
	Notes           *string
	ReviewedBy      *int64
	ReviewedAt      pgtype.Timestamptz
	RejectionReason *string
	UpdatedAt       pgtype.Timestamptz
}

type Donor struct {
	ID           int32
	FullName     *string
	Email        *string
	DOB          pgtype.Date
	Gender       *string
	BloodGroup   *string
	Rhesus       *string
	Contact      *string
	Address      *string
	Password     *string
	LastDonation pgtype.Date
}

type DonorEligibility struct {
	DonorID             int64
	FullName            string
	BloodGroup          *BloodGroup
	Rhesus              *Rhesus
	AgeYears            int32
	LastDonatedAt       interface{}
	DonationsLast12m    *int64
	PermanentlyDeferred *bool
	DeferredUntil       interface{}
	NextEligibleOn      interface{}
	IsEligibleToday     *bool
	Reason              string
}

type DonorProfile struct {
	UserID                int64
	FullName              string
	DateOfBirth           pgtype.Date
	Gender                Gender
	BloodGroup            *BloodGroup
	Rhesus                *Rhesus
	BloodGroupVerifiedAt  pgtype.Timestamptz
	ContactPhone          string
	AddressLine           *string
	City                  *string
	Region                *string
	NationalID            *string
	EmergencyContactName  *string
	EmergencyContactPhone *string
	TotalDonations        int32
	LegacyLastDonation    pgtype.Date
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Hospital struct {
	ID           int64
	Name         string
	LicenseNo    string
	AddressLine  string
	City         string
	Region       string
	Phone        *string
	ContactEmail string
	Status       HospitalStatus
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type InventorySummary struct {
	BloodGroup        BloodGroup
	Rhesus            Rhesus
	ComponentType     ComponentType
	UnitsAvailable    int64
	UnitsReserved     int64
	UnitsQuarantined  int64
	ExpiringWithin72h int64
	ExpiringWithin7d  int64
	NextExpiryAt      interface{}
	VolumeMlAvailable int64
}

type Issuance struct {
	ID                int64
	BloodRequestID    int64
	IssuedAt          pgtype.Timestamptz
	IssuedBy          int64
	ReceivedByName    string
	ReceivedByRole    *string
	DeliveryNoteUrl   *string
	TransportTempC    pgtype.Numeric
	Outcome           IssuanceOutcome
	OutcomeRecordedAt pgtype.Timestamptz
	OutcomeNotes      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type MigrationReject struct {
	ID          int64
	SourceTable string
	SourceID    int64
	Reason      string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type Notification struct {
	ID           int64
	UserID       int64
	Channel      NotificationChannel
	Template     string
	Payload      []byte
	Status       NotificationStatus
	ScheduledFor pgtype.Timestamptz
	SentAt       pgtype.Timestamptz
	Attempts     int16
	FailedReason *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Policy struct {
	ID            int64
	Key           string
	Value         []byte
	Region        string
	Description   *string
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	CreatedBy     *int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Screening struct {
	ID            int64
	AppointmentID int64
	DonorID       int64
	HemoglobinGDl pgtype.Numeric
	BpSystolic    int16
	BpDiastolic   int16
	PulseBpm      int16
	WeightKg      pgtype.Numeric
	TemperatureC  pgtype.Numeric
	Questionnaire []byte
	Outcome       ScreeningOutcome
	DeferredUntil pgtype.Date
	Notes         *string
	ScreenedBy    int64
	ScreenedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type StorageLocation struct {
	ID            int64
	CenterID      int64
	Name          string
	Kind          StorageKind
	TempMinC      pgtype.Numeric
	TempMaxC      pgtype.Numeric
	CapacityUnits *int32
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TestResult struct {
	ID         int64
	DonationID int64
	TestType   string
	Result     TestResultStatus
	IsCurrent  bool
	TestedAt   pgtype.Timestamptz
	TestedBy   *int64
	Instrument *string
	KitLotNo   *string
	Remarks    *string
	RepeatOf   *int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type TestType struct {
	Code         string
	Name         string
	IsMandatory  bool
	Region       string
	DisplayOrder int16
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UnitAllocation struct {
	ID               int64
	BloodRequestID   int64
	UnitID           int64
	IssuanceID       *int64
	CrossmatchResult CrossmatchResult
	CrossmatchAt     pgtype.Timestamptz
	CrossmatchBy     *int64
	AllocatedAt      pgtype.Timestamptz
	AllocatedBy      int64
	ReleasedAt       pgtype.Timestamptz
	ReleaseReason    *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type UnitProvenance struct {
	UnitID              int64
	UnitCode            string
	ComponentType       ComponentType
	BloodGroup          BloodGroup
	Rhesus              Rhesus
	UnitStatus          BloodUnitStatus
	ExpiresAt           pgtype.Timestamptz
	RootUnitID          int64
	SplitDepth          int32
	DonationID          int64
	CollectedAt         pgtype.Timestamptz
	DonationVolumeMl    int32
	BagLotNumber        string
	DonorID             int64
	DonorName           string
	ScreeningID         *int64
	HemoglobinGDl       pgtype.Numeric
	ScreeningOutcome    *ScreeningOutcome
	CenterName          string
	AllTestsNonReactive bool
	TestPanel           []byte
	BloodRequestID      *int64
	AllocatedAt         pgtype.Timestamptz
	CrossmatchResult    *CrossmatchResult
	IssuedAt            pgtype.Timestamptz
	ReceivedByName      *string
	IssuanceOutcome     *IssuanceOutcome
	HospitalName        *string
	PatientRef          *string
}

type UnitStatusEvent struct {
	ID             int64
	UnitID         int64
	FromStatus     *BloodUnitStatus
	ToStatus       BloodUnitStatus
	Reason         *string
	ActorID        *int64
	BloodRequestID *int64
	OccurredAt     pgtype.Timestamptz
}

type User struct {
	ID               int64
	PublicID         pgtype.UUID
	Email            string
	PasswordHash     string
	Role             UserRole
	Status           UserStatus
	Phone            *string
	HospitalID       *int64
	LastLoginAt      pgtype.Timestamptz
	FailedLoginCount int16
	LockedUntil      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeactivatedAt    pgtype.Timestamptz
}
