// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package store

import (
	"context"
)

const listActivePolicies = `-- name: ListActivePolicies :many
SELECT key, region, value, effective_from
FROM active_policies
ORDER BY key, region
`

// Every active policy row, for every key.
//
// The whole set in one query, not a lookup per key: a decision must be made
// against ONE snapshot. Fetching `donor_age_years` and then
// `donation_interval_days.whole_blood` as two round trips lets an administrator
// change a threshold in between, so the decision is made half under the old
// policy and half under the new one — and the version stamped on it would name
// neither.
func (q *Queries) ListActivePolicies(ctx context.Context) ([]ActivePolicy, error) {
	rows, err := q.db.Query(ctx, listActivePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivePolicy{}
	for rows.Next() {
		var i ActivePolicy
		if err := rows.Scan(
			&i.Key,
			&i.Region,
			&i.Value,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
