// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE user_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, acceptInvite, id)
	return err
}

const activateUserWithPassword = `-- name: ActivateUserWithPassword :exec
UPDATE users SET password_hash = $2, status = 'active', deactivated_at = NULL
WHERE id = $1
`

type ActivateUserWithPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) ActivateUserWithPassword(ctx context.Context, arg ActivateUserWithPasswordParams) error {
	_, err := q.db.Exec(ctx, activateUserWithPassword, arg.ID, arg.PasswordHash)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND status = 'active'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users u
WHERE ($1::user_role IS NULL OR u.role = $1::user_role)
  AND ($2::user_status IS NULL OR u.status = $2::user_status)
  AND ($3::text IS NULL OR u.email::text ILIKE '%' || $3::text || '%')
`

type CountUsersParams struct {
	Role   *UserRole
	Status *UserStatus
	Search *string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Role, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO user_invites (user_id, token_hash, invited_by, expires_at)
VALUES ($1, $2, $4, $3)
RETURNING id, user_id, expires_at
`

type CreateInviteParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	InvitedBy *int64
}

type CreateInviteRow struct {
	ID        int64
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.InvitedBy,
	)
	var i CreateInviteRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (email, password_hash, role, status, center_id, hospital_id)
VALUES ($1, $2, $3, 'pending_verification', $4, $5)
RETURNING id, email, role, status, center_id, hospital_id, created_at
`

type CreateInvitedUserParams struct {
	Email        string
	PasswordHash string
	Role         UserRole
	CenterID     *int64
	HospitalID   *int64
}

type CreateInvitedUserRow struct {
	ID         int64
	Email      string
	Role       UserRole
	Status     UserStatus
	CenterID   *int64
	HospitalID *int64
	CreatedAt  pgtype.Timestamptz
}

// Creates the account an invite belongs to. The password hash is a discarded
// random secret: the column CHECK requires bcrypt/argon2 shape, so it cannot be
// a placeholder string, and it must not be anything guessable.
func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (CreateInvitedUserRow, error) {
	row := q.db.QueryRow(ctx, createInvitedUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.CenterID,
		arg.HospitalID,
	)
	var i CreateInvitedUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CenterID,
		&i.HospitalID,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenInviteByTokenHash = `-- name: GetOpenInviteByTokenHash :one
SELECT i.id, i.user_id, i.expires_at, u.email, u.role, u.status
FROM user_invites i JOIN users u ON u.id = i.user_id
WHERE i.token_hash = $1 AND i.accepted_at IS NULL
`

type GetOpenInviteByTokenHashRow struct {
	ID        int64
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	Email     string
	Role      UserRole
	Status    UserStatus
}

func (q *Queries) GetOpenInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetOpenInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getOpenInviteByTokenHash, tokenHash)
	var i GetOpenInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Email,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, role, status, center_id, hospital_id, last_login_at, created_at
FROM users WHERE id = $1
`

type GetUserRow struct {
	ID          int64
	Email       string
	Role        UserRole
	Status      UserStatus
	CenterID    *int64
	HospitalID  *int64
	LastLoginAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CenterID,
		&i.HospitalID,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, status, center_id, hospital_id, last_login_at, created_at
FROM users WHERE email = $1::citext
`

type GetUserByEmailRow struct {
	ID          int64
	Email       string
	Role        UserRole
	Status      UserStatus
	CenterID    *int64
	HospitalID  *int64
	LastLoginAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CenterID,
		&i.HospitalID,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many

SELECT u.id, u.email, u.role, u.status, u.center_id, u.hospital_id,
       u.last_login_at, u.created_at,
       (i.id IS NOT NULL)::boolean AS invite_pending
FROM users u
LEFT JOIN user_invites i ON i.user_id = u.id AND i.accepted_at IS NULL AND i.expires_at > now()
WHERE ($1::user_role IS NULL OR u.role = $1::user_role)
  AND ($2::user_status IS NULL OR u.status = $2::user_status)
  AND ($3::text IS NULL OR u.email::text ILIKE '%' || $3::text || '%')
ORDER BY u.id
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Role   *UserRole
	Status *UserStatus
	Search *string
	Off    int32
	Lim    int32
}

type ListUsersRow struct {
	ID            int64
	Email         string
	Role          UserRole
	Status        UserStatus
	CenterID      *int64
	HospitalID    *int64
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	InvitePending bool
}

// User administration (WI-18, FR-66).
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Role,
		arg.Status,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CenterID,
			&i.HospitalID,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.InvitePending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAndCountAdmins = `-- name: LockAndCountAdmins :one
SELECT count(*) FROM (
    SELECT 1 FROM users WHERE role = 'admin' AND status = 'active' FOR UPDATE
) AS locked
`

// The same count, but holding a row lock on every active admin.
//
// `ensureNotLastAdmin` counted outside any transaction, so two concurrent
// demotions of the last two admins both saw 2 and both succeeded — leaving zero
// admins, from which there is no recovery short of SQL. Locking the rows the
// decision depends on serialises the two callers.
func (q *Queries) LockAndCountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, lockAndCountAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const resetInvitedUser = `-- name: ResetInvitedUser :exec
UPDATE users
   SET password_hash = $2, role = $3, status = 'pending_verification',
       center_id = $4, hospital_id = $5,
       deactivated_at = NULL
WHERE id = $1 AND status = 'pending_verification'
`

type ResetInvitedUserParams struct {
	ID           int64
	PasswordHash string
	Role         UserRole
	CenterID     *int64
	HospitalID   *int64
}

// Re-inviting is expected: the first link expires, or never arrives. The old
// account row is reused rather than refused, so the user id, and anything
// already pointing at it, survives.
func (q *Queries) ResetInvitedUser(ctx context.Context, arg ResetInvitedUserParams) error {
	_, err := q.db.Exec(ctx, resetInvitedUser,
		arg.ID,
		arg.PasswordHash,
		arg.Role,
		arg.CenterID,
		arg.HospitalID,
	)
	return err
}

const revokeOpenInvitesForUser = `-- name: RevokeOpenInvitesForUser :exec
UPDATE user_invites SET accepted_at = now()
WHERE user_id = $1 AND accepted_at IS NULL
`

func (q *Queries) RevokeOpenInvitesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeOpenInvitesForUser, userID)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2, center_id = $3, hospital_id = $4
WHERE id = $1
`

type SetUserRoleParams struct {
	ID         int64
	Role       UserRole
	CenterID   *int64
	HospitalID *int64
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole,
		arg.ID,
		arg.Role,
		arg.CenterID,
		arg.HospitalID,
	)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users
   SET status = $2,
       deactivated_at = CASE WHEN $2::user_status = 'deactivated' THEN now() ELSE NULL END
WHERE id = $1
`

type SetUserStatusParams struct {
	ID     int64
	Status UserStatus
}

// `deactivated_at` is kept in step with the status by users_deactivated_sync,
// so it is set and cleared here rather than left to a separate statement that
// could be forgotten.
func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status)
	return err
}
